// <auto-generated />
using System;
using FileSharing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileSharing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230910063328_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("FileSharing.Models.Entry", b =>
                {
                    b.Property<string>("guid")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("aesKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("customId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("expiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("iv")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("maxNumOfDownloads")
                        .HasColumnType("INTEGER");

                    b.HasKey("guid");

                    b.HasIndex("customId")
                        .IsUnique();

                    b.ToTable("Entry");
                });
#pragma warning restore 612, 618
        }
    }
}
